// Code generated by entc, DO NOT EDIT.

package tableb

const (
	// Label holds the string label denoting the tableb type in the database.
	Label = "tableb"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldB holds the string denoting the b field in the database.
	FieldB = "b"
	// Table holds the table name of the tableb in the database.
	Table = "table_bs"
)

// Columns holds all SQL columns for tableb fields.
var Columns = []string{
	FieldID,
	FieldB,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
