// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TableAsColumns holds the columns for the "table_as" table.
	TableAsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "a", Type: field.TypeJSON},
	}
	// TableAsTable holds the schema information for the "table_as" table.
	TableAsTable = &schema.Table{
		Name:        "table_as",
		Columns:     TableAsColumns,
		PrimaryKey:  []*schema.Column{TableAsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// TableBsColumns holds the columns for the "table_bs" table.
	TableBsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "b", Type: field.TypeJSON},
	}
	// TableBsTable holds the schema information for the "table_bs" table.
	TableBsTable = &schema.Table{
		Name:        "table_bs",
		Columns:     TableBsColumns,
		PrimaryKey:  []*schema.Column{TableBsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TableAsTable,
		TableBsTable,
	}
)

func init() {
}
