// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/washanhanzi/ent-same-package-name/ent/predicate"
	"github.com/washanhanzi/ent-same-package-name/ent/tablea"
)

// TableADelete is the builder for deleting a TableA entity.
type TableADelete struct {
	config
	hooks    []Hook
	mutation *TableAMutation
}

// Where adds a new predicate to the TableADelete builder.
func (ta *TableADelete) Where(ps ...predicate.TableA) *TableADelete {
	ta.mutation.predicates = append(ta.mutation.predicates, ps...)
	return ta
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ta *TableADelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ta.hooks) == 0 {
		affected, err = ta.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TableAMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ta.mutation = mutation
			affected, err = ta.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ta.hooks) - 1; i >= 0; i-- {
			mut = ta.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ta.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ta *TableADelete) ExecX(ctx context.Context) int {
	n, err := ta.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ta *TableADelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tablea.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tablea.FieldID,
			},
		},
	}
	if ps := ta.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ta.driver, _spec)
}

// TableADeleteOne is the builder for deleting a single TableA entity.
type TableADeleteOne struct {
	ta *TableADelete
}

// Exec executes the deletion query.
func (tao *TableADeleteOne) Exec(ctx context.Context) error {
	n, err := tao.ta.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tablea.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tao *TableADeleteOne) ExecX(ctx context.Context) {
	tao.ta.ExecX(ctx)
}
