// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/washanhanzi/ent-same-package-name/a/entity"
	"github.com/washanhanzi/ent-same-package-name/ent/tablea"
)

// TableACreate is the builder for creating a TableA entity.
type TableACreate struct {
	config
	mutation *TableAMutation
	hooks    []Hook
}

// SetA sets the "a" field.
func (ta *TableACreate) SetA(e entity.A) *TableACreate {
	ta.mutation.SetA(e)
	return ta
}

// Mutation returns the TableAMutation object of the builder.
func (ta *TableACreate) Mutation() *TableAMutation {
	return ta.mutation
}

// Save creates the TableA in the database.
func (ta *TableACreate) Save(ctx context.Context) (*TableA, error) {
	var (
		err  error
		node *TableA
	)
	if len(ta.hooks) == 0 {
		if err = ta.check(); err != nil {
			return nil, err
		}
		node, err = ta.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TableAMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ta.check(); err != nil {
				return nil, err
			}
			ta.mutation = mutation
			node, err = ta.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ta.hooks) - 1; i >= 0; i-- {
			mut = ta.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ta.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ta *TableACreate) SaveX(ctx context.Context) *TableA {
	v, err := ta.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (ta *TableACreate) check() error {
	if _, ok := ta.mutation.A(); !ok {
		return &ValidationError{Name: "a", err: errors.New("ent: missing required field \"a\"")}
	}
	return nil
}

func (ta *TableACreate) sqlSave(ctx context.Context) (*TableA, error) {
	_node, _spec := ta.createSpec()
	if err := sqlgraph.CreateNode(ctx, ta.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ta *TableACreate) createSpec() (*TableA, *sqlgraph.CreateSpec) {
	var (
		_node = &TableA{config: ta.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tablea.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tablea.FieldID,
			},
		}
	)
	if value, ok := ta.mutation.A(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: tablea.FieldA,
		})
		_node.A = value
	}
	return _node, _spec
}

// TableACreateBulk is the builder for creating many TableA entities in bulk.
type TableACreateBulk struct {
	config
	builders []*TableACreate
}

// Save creates the TableA entities in the database.
func (tab *TableACreateBulk) Save(ctx context.Context) ([]*TableA, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tab.builders))
	nodes := make([]*TableA, len(tab.builders))
	mutators := make([]Mutator, len(tab.builders))
	for i := range tab.builders {
		func(i int, root context.Context) {
			builder := tab.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TableAMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tab.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tab.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tab.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tab *TableACreateBulk) SaveX(ctx context.Context) []*TableA {
	v, err := tab.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
