// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/washanhanzi/ent-same-package-name/a/entity"
	"github.com/washanhanzi/ent-same-package-name/ent/predicate"
	"github.com/washanhanzi/ent-same-package-name/ent/tablea"
)

// TableAUpdate is the builder for updating TableA entities.
type TableAUpdate struct {
	config
	hooks    []Hook
	mutation *TableAMutation
}

// Where adds a new predicate for the TableAUpdate builder.
func (ta *TableAUpdate) Where(ps ...predicate.TableA) *TableAUpdate {
	ta.mutation.predicates = append(ta.mutation.predicates, ps...)
	return ta
}

// SetA sets the "a" field.
func (ta *TableAUpdate) SetA(e entity.A) *TableAUpdate {
	ta.mutation.SetA(e)
	return ta
}

// Mutation returns the TableAMutation object of the builder.
func (ta *TableAUpdate) Mutation() *TableAMutation {
	return ta.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ta *TableAUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ta.hooks) == 0 {
		affected, err = ta.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TableAMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ta.mutation = mutation
			affected, err = ta.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ta.hooks) - 1; i >= 0; i-- {
			mut = ta.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ta.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ta *TableAUpdate) SaveX(ctx context.Context) int {
	affected, err := ta.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ta *TableAUpdate) Exec(ctx context.Context) error {
	_, err := ta.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ta *TableAUpdate) ExecX(ctx context.Context) {
	if err := ta.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ta *TableAUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tablea.Table,
			Columns: tablea.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tablea.FieldID,
			},
		},
	}
	if ps := ta.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ta.mutation.A(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: tablea.FieldA,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ta.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tablea.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// TableAUpdateOne is the builder for updating a single TableA entity.
type TableAUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TableAMutation
}

// SetA sets the "a" field.
func (tao *TableAUpdateOne) SetA(e entity.A) *TableAUpdateOne {
	tao.mutation.SetA(e)
	return tao
}

// Mutation returns the TableAMutation object of the builder.
func (tao *TableAUpdateOne) Mutation() *TableAMutation {
	return tao.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tao *TableAUpdateOne) Select(field string, fields ...string) *TableAUpdateOne {
	tao.fields = append([]string{field}, fields...)
	return tao
}

// Save executes the query and returns the updated TableA entity.
func (tao *TableAUpdateOne) Save(ctx context.Context) (*TableA, error) {
	var (
		err  error
		node *TableA
	)
	if len(tao.hooks) == 0 {
		node, err = tao.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TableAMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tao.mutation = mutation
			node, err = tao.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tao.hooks) - 1; i >= 0; i-- {
			mut = tao.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tao.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tao *TableAUpdateOne) SaveX(ctx context.Context) *TableA {
	node, err := tao.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tao *TableAUpdateOne) Exec(ctx context.Context) error {
	_, err := tao.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tao *TableAUpdateOne) ExecX(ctx context.Context) {
	if err := tao.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tao *TableAUpdateOne) sqlSave(ctx context.Context) (_node *TableA, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tablea.Table,
			Columns: tablea.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tablea.FieldID,
			},
		},
	}
	id, ok := tao.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing TableA.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := tao.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tablea.FieldID)
		for _, f := range fields {
			if !tablea.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tablea.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tao.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tao.mutation.A(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: tablea.FieldA,
		})
	}
	_node = &TableA{config: tao.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tao.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tablea.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
