// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/washanhanzi/ent-same-package-name/ent/predicate"
	"github.com/washanhanzi/ent-same-package-name/ent/tablea"
)

// TableAQuery is the builder for querying TableA entities.
type TableAQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TableA
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TableAQuery builder.
func (ta *TableAQuery) Where(ps ...predicate.TableA) *TableAQuery {
	ta.predicates = append(ta.predicates, ps...)
	return ta
}

// Limit adds a limit step to the query.
func (ta *TableAQuery) Limit(limit int) *TableAQuery {
	ta.limit = &limit
	return ta
}

// Offset adds an offset step to the query.
func (ta *TableAQuery) Offset(offset int) *TableAQuery {
	ta.offset = &offset
	return ta
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ta *TableAQuery) Unique(unique bool) *TableAQuery {
	ta.unique = &unique
	return ta
}

// Order adds an order step to the query.
func (ta *TableAQuery) Order(o ...OrderFunc) *TableAQuery {
	ta.order = append(ta.order, o...)
	return ta
}

// First returns the first TableA entity from the query.
// Returns a *NotFoundError when no TableA was found.
func (ta *TableAQuery) First(ctx context.Context) (*TableA, error) {
	nodes, err := ta.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tablea.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ta *TableAQuery) FirstX(ctx context.Context) *TableA {
	node, err := ta.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TableA ID from the query.
// Returns a *NotFoundError when no TableA ID was found.
func (ta *TableAQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ta.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tablea.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ta *TableAQuery) FirstIDX(ctx context.Context) int {
	id, err := ta.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TableA entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TableA entity is not found.
// Returns a *NotFoundError when no TableA entities are found.
func (ta *TableAQuery) Only(ctx context.Context) (*TableA, error) {
	nodes, err := ta.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tablea.Label}
	default:
		return nil, &NotSingularError{tablea.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ta *TableAQuery) OnlyX(ctx context.Context) *TableA {
	node, err := ta.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TableA ID in the query.
// Returns a *NotSingularError when exactly one TableA ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ta *TableAQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ta.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tablea.Label}
	default:
		err = &NotSingularError{tablea.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ta *TableAQuery) OnlyIDX(ctx context.Context) int {
	id, err := ta.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TableAs.
func (ta *TableAQuery) All(ctx context.Context) ([]*TableA, error) {
	if err := ta.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ta.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ta *TableAQuery) AllX(ctx context.Context) []*TableA {
	nodes, err := ta.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TableA IDs.
func (ta *TableAQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ta.Select(tablea.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ta *TableAQuery) IDsX(ctx context.Context) []int {
	ids, err := ta.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ta *TableAQuery) Count(ctx context.Context) (int, error) {
	if err := ta.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ta.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ta *TableAQuery) CountX(ctx context.Context) int {
	count, err := ta.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ta *TableAQuery) Exist(ctx context.Context) (bool, error) {
	if err := ta.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ta.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ta *TableAQuery) ExistX(ctx context.Context) bool {
	exist, err := ta.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TableAQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ta *TableAQuery) Clone() *TableAQuery {
	if ta == nil {
		return nil
	}
	return &TableAQuery{
		config:     ta.config,
		limit:      ta.limit,
		offset:     ta.offset,
		order:      append([]OrderFunc{}, ta.order...),
		predicates: append([]predicate.TableA{}, ta.predicates...),
		// clone intermediate query.
		sql:  ta.sql.Clone(),
		path: ta.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		A entity.A `json:"a,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TableA.Query().
//		GroupBy(tablea.FieldA).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ta *TableAQuery) GroupBy(field string, fields ...string) *TableAGroupBy {
	group := &TableAGroupBy{config: ta.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ta.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ta.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		A entity.A `json:"a,omitempty"`
//	}
//
//	client.TableA.Query().
//		Select(tablea.FieldA).
//		Scan(ctx, &v)
//
func (ta *TableAQuery) Select(field string, fields ...string) *TableASelect {
	ta.fields = append([]string{field}, fields...)
	return &TableASelect{TableAQuery: ta}
}

func (ta *TableAQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ta.fields {
		if !tablea.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ta.path != nil {
		prev, err := ta.path(ctx)
		if err != nil {
			return err
		}
		ta.sql = prev
	}
	return nil
}

func (ta *TableAQuery) sqlAll(ctx context.Context) ([]*TableA, error) {
	var (
		nodes = []*TableA{}
		_spec = ta.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TableA{config: ta.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ta.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ta *TableAQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ta.querySpec()
	return sqlgraph.CountNodes(ctx, ta.driver, _spec)
}

func (ta *TableAQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ta.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ta *TableAQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tablea.Table,
			Columns: tablea.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tablea.FieldID,
			},
		},
		From:   ta.sql,
		Unique: true,
	}
	if unique := ta.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ta.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tablea.FieldID)
		for i := range fields {
			if fields[i] != tablea.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ta.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ta.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ta.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ta.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ta *TableAQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ta.driver.Dialect())
	t1 := builder.Table(tablea.Table)
	selector := builder.Select(t1.Columns(tablea.Columns...)...).From(t1)
	if ta.sql != nil {
		selector = ta.sql
		selector.Select(selector.Columns(tablea.Columns...)...)
	}
	for _, p := range ta.predicates {
		p(selector)
	}
	for _, p := range ta.order {
		p(selector)
	}
	if offset := ta.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ta.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TableAGroupBy is the group-by builder for TableA entities.
type TableAGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tab *TableAGroupBy) Aggregate(fns ...AggregateFunc) *TableAGroupBy {
	tab.fns = append(tab.fns, fns...)
	return tab
}

// Scan applies the group-by query and scans the result into the given value.
func (tab *TableAGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tab.path(ctx)
	if err != nil {
		return err
	}
	tab.sql = query
	return tab.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tab *TableAGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tab.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tab *TableAGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tab.fields) > 1 {
		return nil, errors.New("ent: TableAGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tab.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tab *TableAGroupBy) StringsX(ctx context.Context) []string {
	v, err := tab.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tab *TableAGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tab.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tablea.Label}
	default:
		err = fmt.Errorf("ent: TableAGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tab *TableAGroupBy) StringX(ctx context.Context) string {
	v, err := tab.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tab *TableAGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tab.fields) > 1 {
		return nil, errors.New("ent: TableAGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tab.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tab *TableAGroupBy) IntsX(ctx context.Context) []int {
	v, err := tab.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tab *TableAGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tab.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tablea.Label}
	default:
		err = fmt.Errorf("ent: TableAGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tab *TableAGroupBy) IntX(ctx context.Context) int {
	v, err := tab.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tab *TableAGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tab.fields) > 1 {
		return nil, errors.New("ent: TableAGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tab.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tab *TableAGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tab.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tab *TableAGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tab.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tablea.Label}
	default:
		err = fmt.Errorf("ent: TableAGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tab *TableAGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tab.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tab *TableAGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tab.fields) > 1 {
		return nil, errors.New("ent: TableAGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tab.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tab *TableAGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tab.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tab *TableAGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tab.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tablea.Label}
	default:
		err = fmt.Errorf("ent: TableAGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tab *TableAGroupBy) BoolX(ctx context.Context) bool {
	v, err := tab.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tab *TableAGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tab.fields {
		if !tablea.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tab.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tab.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tab *TableAGroupBy) sqlQuery() *sql.Selector {
	selector := tab.sql
	columns := make([]string, 0, len(tab.fields)+len(tab.fns))
	columns = append(columns, tab.fields...)
	for _, fn := range tab.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(tab.fields...)
}

// TableASelect is the builder for selecting fields of TableA entities.
type TableASelect struct {
	*TableAQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ta *TableASelect) Scan(ctx context.Context, v interface{}) error {
	if err := ta.prepareQuery(ctx); err != nil {
		return err
	}
	ta.sql = ta.TableAQuery.sqlQuery(ctx)
	return ta.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ta *TableASelect) ScanX(ctx context.Context, v interface{}) {
	if err := ta.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ta *TableASelect) Strings(ctx context.Context) ([]string, error) {
	if len(ta.fields) > 1 {
		return nil, errors.New("ent: TableASelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ta.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ta *TableASelect) StringsX(ctx context.Context) []string {
	v, err := ta.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ta *TableASelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ta.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tablea.Label}
	default:
		err = fmt.Errorf("ent: TableASelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ta *TableASelect) StringX(ctx context.Context) string {
	v, err := ta.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ta *TableASelect) Ints(ctx context.Context) ([]int, error) {
	if len(ta.fields) > 1 {
		return nil, errors.New("ent: TableASelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ta.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ta *TableASelect) IntsX(ctx context.Context) []int {
	v, err := ta.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ta *TableASelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ta.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tablea.Label}
	default:
		err = fmt.Errorf("ent: TableASelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ta *TableASelect) IntX(ctx context.Context) int {
	v, err := ta.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ta *TableASelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ta.fields) > 1 {
		return nil, errors.New("ent: TableASelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ta.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ta *TableASelect) Float64sX(ctx context.Context) []float64 {
	v, err := ta.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ta *TableASelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ta.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tablea.Label}
	default:
		err = fmt.Errorf("ent: TableASelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ta *TableASelect) Float64X(ctx context.Context) float64 {
	v, err := ta.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ta *TableASelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ta.fields) > 1 {
		return nil, errors.New("ent: TableASelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ta.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ta *TableASelect) BoolsX(ctx context.Context) []bool {
	v, err := ta.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ta *TableASelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ta.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tablea.Label}
	default:
		err = fmt.Errorf("ent: TableASelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ta *TableASelect) BoolX(ctx context.Context) bool {
	v, err := ta.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ta *TableASelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ta.sqlQuery().Query()
	if err := ta.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ta *TableASelect) sqlQuery() sql.Querier {
	selector := ta.sql
	selector.Select(selector.Columns(ta.fields...)...)
	return selector
}
