// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/washanhanzi/ent-same-package-name/b/entity"
	"github.com/washanhanzi/ent-same-package-name/ent/predicate"
	"github.com/washanhanzi/ent-same-package-name/ent/tableb"
)

// TableBUpdate is the builder for updating TableB entities.
type TableBUpdate struct {
	config
	hooks    []Hook
	mutation *TableBMutation
}

// Where adds a new predicate for the TableBUpdate builder.
func (tb *TableBUpdate) Where(ps ...predicate.TableB) *TableBUpdate {
	tb.mutation.predicates = append(tb.mutation.predicates, ps...)
	return tb
}

// SetB sets the "b" field.
func (tb *TableBUpdate) SetB(e entity.B) *TableBUpdate {
	tb.mutation.SetB(e)
	return tb
}

// Mutation returns the TableBMutation object of the builder.
func (tb *TableBUpdate) Mutation() *TableBMutation {
	return tb.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tb *TableBUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tb.hooks) == 0 {
		affected, err = tb.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TableBMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tb.mutation = mutation
			affected, err = tb.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tb.hooks) - 1; i >= 0; i-- {
			mut = tb.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tb.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tb *TableBUpdate) SaveX(ctx context.Context) int {
	affected, err := tb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tb *TableBUpdate) Exec(ctx context.Context) error {
	_, err := tb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tb *TableBUpdate) ExecX(ctx context.Context) {
	if err := tb.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tb *TableBUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tableb.Table,
			Columns: tableb.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tableb.FieldID,
			},
		},
	}
	if ps := tb.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tb.mutation.B(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: tableb.FieldB,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tb.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tableb.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// TableBUpdateOne is the builder for updating a single TableB entity.
type TableBUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TableBMutation
}

// SetB sets the "b" field.
func (tbo *TableBUpdateOne) SetB(e entity.B) *TableBUpdateOne {
	tbo.mutation.SetB(e)
	return tbo
}

// Mutation returns the TableBMutation object of the builder.
func (tbo *TableBUpdateOne) Mutation() *TableBMutation {
	return tbo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tbo *TableBUpdateOne) Select(field string, fields ...string) *TableBUpdateOne {
	tbo.fields = append([]string{field}, fields...)
	return tbo
}

// Save executes the query and returns the updated TableB entity.
func (tbo *TableBUpdateOne) Save(ctx context.Context) (*TableB, error) {
	var (
		err  error
		node *TableB
	)
	if len(tbo.hooks) == 0 {
		node, err = tbo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TableBMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tbo.mutation = mutation
			node, err = tbo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tbo.hooks) - 1; i >= 0; i-- {
			mut = tbo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tbo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tbo *TableBUpdateOne) SaveX(ctx context.Context) *TableB {
	node, err := tbo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tbo *TableBUpdateOne) Exec(ctx context.Context) error {
	_, err := tbo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tbo *TableBUpdateOne) ExecX(ctx context.Context) {
	if err := tbo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tbo *TableBUpdateOne) sqlSave(ctx context.Context) (_node *TableB, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tableb.Table,
			Columns: tableb.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tableb.FieldID,
			},
		},
	}
	id, ok := tbo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing TableB.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := tbo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tableb.FieldID)
		for _, f := range fields {
			if !tableb.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tableb.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tbo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tbo.mutation.B(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: tableb.FieldB,
		})
	}
	_node = &TableB{config: tbo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tbo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tableb.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
