// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/washanhanzi/ent-same-package-name/b/entity"
	"github.com/washanhanzi/ent-same-package-name/ent/tableb"
)

// TableB is the model entity for the TableB schema.
type TableB struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// B holds the value of the "b" field.
	B entity.B `json:"b,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TableB) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case tableb.FieldB:
			values[i] = new([]byte)
		case tableb.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type TableB", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TableB fields.
func (t *TableB) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tableb.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case tableb.FieldB:

			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field b", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &t.B); err != nil {
					return fmt.Errorf("unmarshal field b: %w", err)
				}
			}
		}
	}
	return nil
}

// Update returns a builder for updating this TableB.
// Note that you need to call TableB.Unwrap() before calling this method if this TableB
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *TableB) Update() *TableBUpdateOne {
	return (&TableBClient{config: t.config}).UpdateOne(t)
}

// Unwrap unwraps the TableB entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *TableB) Unwrap() *TableB {
	tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: TableB is not a transactional entity")
	}
	t.config.driver = tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *TableB) String() string {
	var builder strings.Builder
	builder.WriteString("TableB(")
	builder.WriteString(fmt.Sprintf("id=%v", t.ID))
	builder.WriteString(", b=")
	builder.WriteString(fmt.Sprintf("%v", t.B))
	builder.WriteByte(')')
	return builder.String()
}

// TableBs is a parsable slice of TableB.
type TableBs []*TableB

func (t TableBs) config(cfg config) {
	for _i := range t {
		t[_i].config = cfg
	}
}
