// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TableA is the predicate function for tablea builders.
type TableA func(*sql.Selector)

// TableB is the predicate function for tableb builders.
type TableB func(*sql.Selector)
